baseURL = "https://mapishu.netlify.com"
languageCode = "en-us"
paginate = 6
subtitle = "Shiatsu & bien-être"
summaryLength = "10"
theme = "influencer-hugo"
title = "Mapishu"
[[menu.main]]
URL = "Accueil"
name = "Accueil"
weight = 1
[[menu.main]]
URL = "shiatsu"
name = "Shiatsu"
weight = 2
[[menu.main]]
URL = "review"
name = "Reviews"
weight = 3
[[menu.main]]
URL = "author"
name = "Author"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = "Alan Pacaud"
copyright = "Copyright &copy; 2020 [Alan Pacaud](https://github.com/alanpacaud) All Rights Reserved"
description = "Shiatsu & bien-être"
googleAnalitycsID = ""
home = "Accueil"
logo = "images/uploads/logomapishu.png"
[params.footer]
content = "Each theme featured at the Bootstrap marketplace has been reviewed by Bootstrap's creators.Lorem ipsum dolor sit amet, consectetur adipisicing elit."
[params.navButton]
enable = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.share]]
icon = "ti-facebook"
link = "https://www.facebook.com/mariemapishu"
title = "facebook"
[[params.share]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.share]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
[[params.share]]
icon = "ti-github"
link = "https://github.com/alanpacaud"
title = "github"
